templates/fungible-asset-template/frontend/package.json, templates/fungible-asset-template/frontend/src/main.tsx, templates/fungible-asset-template/package.json, templates/fungible-asset-template/scripts/gen_abi.sh, templates/fungible-asset-template/scripts/get_module_addr.sh, templates/fungible-asset-template/scripts/init.js, templates/fungible-asset-template/scripts/move/compile.js, templates/fungible-asset-template/scripts/move/publish.js, templates/fungible-asset-template/scripts/move/test.js, templates/fungible-asset-template/scripts/update_env.js
Use Node functions when running Move commands in the tool for OS compatibility (instead of running Mac only supported commands)
Tested on both Mac and Windows machines
=> Use pure node functions to run move commands for os compatibility

src/types.ts, src/workflowOptions.ts
Remove `devnet` as a network option since we dont support it with the initial templates (Irys only supports mainnet / testnet)
=> Remove devnet from network options

templates/digital-asset-template/scripts/update_env.js, templates/fungible-asset-template/scripts/update_env.js
There is a bug if we run `npm run move:init` multiple times (so we create new profile accounts) the `VITE_MODULE_ADDRESS` variable is being appended instead of replaced
=> Override VITE_MODULE_ADDRESS variable if exists

templates/digital-asset-template/move/sources/launchpad.move
1. Add view function to get start and end time of active or next mint stage. Frontend can first call `get_active_or_next_mint_stage()` to the stage name, then call `get_mint_stage_start_and_end_time()`
2. Default public mint end time to 100 years so frontend can set it to undefined.
=> Various improvements on NFT contract

src/generateDapp.ts, src/types.ts, src/workflowOptions.ts
With the latest contract changes https://github.com/aptos-labs/create-aptos-dapp/pull/95 , we update the wizard tool to show next steps as
```
Success! You're ready to start building your dapp on Aptos.
Next steps:
1. cd ${projectName}
2. npm run dev
3. Follow the instructions for the ${selection.template.name} template on ${selection.template.doc}
```
In addition, we write the `VITE_CREATOR_ADDRESS=""` to the project `.env` file so later the developer can update it with the account address
=> Update wizard flow following latest contract changes

templates/digital-asset-template/frontend/components/WalletProvider.tsx, templates/digital-asset-template/frontend/components/WalletSelector.tsx, templates/digital-asset-template/frontend/components/ui/input.tsx, templates/digital-asset-template/frontend/main.tsx, templates/digital-asset-template/frontend/pages/Mint/components/HeroSection.tsx, templates/digital-asset-template/frontend/pages/Mint/components/OurTeamSection.tsx, templates/digital-asset-template/frontend/pages/Mint/components/Socials.tsx, templates/digital-asset-template/frontend/pages/Mint/index.tsx, templates/digital-asset-template/package.json, templates/fungible-asset-template/frontend/components/WalletProvider.tsx, templates/fungible-asset-template/frontend/components/WalletSelector.tsx, templates/fungible-asset-template/frontend/components/ui/input.tsx, templates/fungible-asset-template/frontend/main.tsx, templates/fungible-asset-template/frontend/pages/Mint/components/HeroSection.tsx, templates/fungible-asset-template/frontend/pages/Mint/components/Socials.tsx, templates/fungible-asset-template/frontend/pages/Mint/index.tsx, templates/fungible-asset-template/package.json
While working on the front-end docs for CAD, I was thinking about adding some instructions for how to add dark mode. To see how easy it would be, I tried adding the shadcn theme provider to one of the dapps I generated from the template and almost everything worked out of the box — there were just a few elements that needed a little more CSS to support dark mode. This PR fixes those elements so that dark mode is as easy as adding the theme provider and a theme toggle.
While I was in the codebase, I did a little misc. cleanup:
- Remove the antd wallet adapter from the template dependencies
- Update to the latest shadcn wallet selector
- Add Toaster to the templates so that wallet errors don't go to the void
=> Support dark mode + minor UI cleanup

templates/digital-asset-template/frontend/components/ui/alert-dialog.tsx, templates/digital-asset-template/frontend/components/ui/button.tsx, templates/digital-asset-template/frontend/components/ui/confirm-button.tsx, templates/digital-asset-template/frontend/components/ui/date-time-input.tsx, templates/digital-asset-template/frontend/components/ui/input.tsx, templates/digital-asset-template/frontend/components/ui/labeled-input.tsx, templates/digital-asset-template/frontend/pages/CreateCollection.tsx, templates/digital-asset-template/frontend/utils/Irys.ts, templates/digital-asset-template/frontend/utils/assetsUploader.ts, templates/digital-asset-template/package.json, templates/fungible-asset-template/frontend/components/ui/alert-dialog.tsx, templates/fungible-asset-template/frontend/components/ui/button.tsx, templates/fungible-asset-template/frontend/components/ui/confirm-button.tsx, templates/fungible-asset-template/frontend/components/ui/date-time-input.tsx, templates/fungible-asset-template/frontend/components/ui/labeled-input.tsx, templates/fungible-asset-template/frontend/pages/CreateFungibleAsset.tsx, templates/fungible-asset-template/frontend/utils/Irys.ts, templates/fungible-asset-template/package.json
This PR refactors the create collection screen for digital assets a bit to fix a few of our issues:
- If uploading a collection fails, you need to first clear it (which will trigger messages) and then re-select the collection
-  "decentrelized" is spelled wrong
- Using `alert` to communicate with the user when creating a collection is not great UX
~Note, I will go through the fungible flow as well after this PR lands or gets changed based on feedback.~
Both flows are now updated. 
https://github.com/aptos-labs/create-aptos-dapp/assets/694324/a90777d5-3fb5-4695-b894-ca5463d14b7a
~https://github.com/aptos-labs/create-aptos-dapp/assets/694324/78a03985-3005-4683-bced-18ca8d40e056~
=> Refactors create collection form for digital

templates/digital-asset-template/frontend/pages/CreateCollection.tsx, templates/digital-asset-template/frontend/pages/Mint/components/HeroSection.tsx, templates/digital-asset-template/move/sources/launchpad.move, templates/fungible-asset-template/frontend/constants.ts, templates/fungible-asset-template/frontend/pages/CreateFungibleAsset.tsx, templates/fungible-asset-template/frontend/pages/Mint/components/HeroSection.tsx, templates/fungible-asset-template/move/sources/launchpad.move, templates/fungible-asset-template/scripts/move/compile.js, templates/fungible-asset-template/scripts/move/publish.js
When it comes to amount, all number on chain should be in smallest unit. Previously `mint_fee_per_fa` is in smallest unit of APT for smallest unit of FA, rename it to `mint_fee_per_smallest_unit_of_fa` to avoid confusion and handle conversion on the UI.
Tested e2e by creating a FA with mint fee per FA set to 0.12 on the UI, FA has 3 decimals. I tried to mint 1 on UI which costs me 0.12 APT, which looks right.
=> fix mint fee unit

.gitignore, templates/digital-asset-template/frontend/App.tsx, templates/digital-asset-template/frontend/components/Header.tsx, templates/digital-asset-template/frontend/components/LaunchpadHeader.tsx, templates/digital-asset-template/frontend/components/UploadSpinner.tsx, templates/digital-asset-template/frontend/components/WalletProvider.tsx, templates/digital-asset-template/frontend/components/WalletSelector.tsx, templates/digital-asset-template/frontend/config.ts, templates/digital-asset-template/frontend/entry-functions/create_collection.ts, templates/digital-asset-template/frontend/entry-functions/mint_nft.ts, templates/digital-asset-template/frontend/hooks/useGetCollectionData.ts, templates/digital-asset-template/frontend/hooks/useGetCollections.tsx, templates/digital-asset-template/frontend/main.tsx, templates/digital-asset-template/frontend/pages/CreateCollection.tsx, templates/digital-asset-template/frontend/pages/Mint/components/BannerSection.tsx, templates/digital-asset-template/frontend/pages/Mint/components/ConnectWalletAlert.tsx, templates/digital-asset-template/frontend/pages/Mint/components/FAQSection.tsx, templates/digital-asset-template/frontend/pages/Mint/components/HeroSection.tsx, templates/digital-asset-template/frontend/pages/Mint/components/OurStorySection.tsx, templates/digital-asset-template/frontend/pages/Mint/components/OurTeamSection.tsx, templates/digital-asset-template/frontend/pages/Mint/components/Socials.tsx, templates/digital-asset-template/frontend/pages/Mint/components/StatsSection.tsx, templates/digital-asset-template/frontend/pages/Mint/components/TriImageBanner.tsx, templates/digital-asset-template/frontend/pages/Mint/index.tsx, templates/digital-asset-template/frontend/pages/MyCollections.tsx, templates/digital-asset-template/frontend/utils/Irys.ts, templates/digital-asset-template/frontend/utils/assetsUploader.ts, templates/digital-asset-template/frontend/view-functions/accountBalance.ts
Clean up and refactor digital asset code, folder structure, file names
=> Clean up and refactor digital asset template

src/generateDapp.ts, templates/digital-asset-template/scripts/init.js, templates/digital-asset-template/scripts/move/compile.js, templates/digital-asset-template/scripts/move/publish.js, templates/digital-asset-template/scripts/update_env.js, templates/fungible-asset-template/scripts/init.js, templates/fungible-asset-template/scripts/move/compile.js, templates/fungible-asset-template/scripts/move/publish.js, templates/fungible-asset-template/scripts/update_env.js
[use cli profile as <project-name>-<network> to not conflict with a possible global config file](https://www.notion.so/aptoslabs/use-cli-profile-as-project-name-network-to-not-conflict-with-a-possible-global-config-file-b857afac76d34bfa97c9884b605cc32e).
Tested with `npm run move:init` and `npm run move:publish`. Full flow worked.
=> Namespaces aptos cli profile with the project name

src/generateDapp.ts, templates/digital-asset-template/scripts/init.js, templates/digital-asset-template/scripts/move/compile.js, templates/digital-asset-template/scripts/move/publish.js, templates/digital-asset-template/scripts/update_env.js, templates/fungible-asset-template/scripts/init.js, templates/fungible-asset-template/scripts/move/compile.js, templates/fungible-asset-template/scripts/move/publish.js, templates/fungible-asset-template/scripts/update_env.js
I was updating the dev docs and ran into an issue when users try and migrate to mainnet. We tell them to manually change the network value in the `.env` file. That complicated the profile namespace a bit. I opted to save the project name, and then derive the profile name in the scripts vs saving the derived value.  
Updating the dev docs now.
=> Fixes namespace issue

templates/digital-asset-template/move/sources/launchpad.move, templates/fungible-asset-template/move/sources/launchpad.move
more context on docs format: https://github.com/aptos-labs/aptos-developer-discussions/discussions/285
=> fix doc format in contract

templates/digital-asset-template/frontend/components/WalletSelector.tsx, templates/fungible-asset-template/frontend/components/WalletSelector.tsx
The public mint page is not guaranteed to be deployed under the `/` route (for example when the dapp is being deployed under www.example.com/homepage), so changing to explicitly not show AptosConnect on Create Collection and My Collections pages.
=> Fix AptosConnect not showing up on the public mint page

templates/boilerplate-template/frontend/entry-functions/transferAPT.ts, templates/boilerplate-template/frontend/view-functions/accountBalance.ts
Because the folders are empty, npm doesnt generate it when installing `npx create-aptos-dapp`. Adding entry and view functions examples
=> [Boilerplate] Add entry and view function examples

CHANGELOG.md, src/generateDapp.ts, src/telemetry.ts, src/types.ts, src/utils/constants.ts, src/utils/helpers.ts, src/workflow.ts, src/workflowOptions.ts
implement a telemetry tool in create-aptos-dapp where we send anonymous data to Google Analytics to understand user usage better and improve the tool. 
When a user goes into the create-aptos-dapp wizard flow, they are asked some questions, and we want to record their decisions.
The implementation is as follows: when the user enters the wizard flow, one of the steps is getting their confirmation on sending anonymous data. The syntax we use is:  Help us improve create-aptos-dapp by sending anonymous data.
=> Add a telemetry tool integration

templates/token-minting-dapp-template/frontend/config.ts, templates/token-minting-dapp-template/frontend/hooks/useGetAssetData.ts, templates/token-minting-dapp-template/frontend/pages/Mint/components/ConnectWalletAlert.tsx
Change copy to say `fa_address` instead of `asset_id`.
Before:
After:
Testing:
```
$pnpm install 
$pnpm dev 
$cd my-aptos-dapp
$npm run move:init
$npm run move:publish
```
Todo: update documentation to support `fa_address` wording
=> Change asset_id -> fa_address

templates/token-staking-dapp-template/move/sources/stake_pool.move, templates/token-staking-dapp-template/move/tests/test_end_to_end.move
We should avoid using table when possible for better performance. Because when we use table, 2 users take at the same time need  go sequentially. (although we still have shared field like `unique_stakers` and `total_stakes` in `StakePool` resource, but we should at least discourage the usage of table if possible.
This PR doesn't affect frontend, it's just internal change to the contract. 
Passed existing unit tests.
=> Avoid using table in stake pool contract

CHANGELOG.md, templates/boilerplate-template/README.md, templates/boilerplate-template/package.json, templates/boilerplate-template/vite.config.ts, templates/nft-minting-dapp-template/README.md, templates/nft-minting-dapp-template/package.json, templates/nft-minting-dapp-template/vite.config.ts, templates/token-minting-dapp-template/README.md, templates/token-minting-dapp-template/package.json, templates/token-minting-dapp-template/vite.config.ts, templates/token-staking-dapp-template/README.md, templates/token-staking-dapp-template/package.json, templates/token-staking-dapp-template/vite.config.ts
This PR adds `npm run deploy` command to easily deploy a static site to Vercel
=> Add a `deploy` npm command

templates/nft-minting-dapp-template/frontend/pages/CreateCollection.tsx, templates/token-minting-dapp-template/frontend/pages/CreateFungibleAsset.tsx
Since AptosConnect is not yet supported by Irys (which is the service CAD uses to upload files with) we add a Warning on only the "create" page for nft and token templates for when the dev is connected with a Google wallet
=> Add a Google wallet not supported warning on file uploading page

CHANGELOG.md, pnpm-lock.yaml, src/generateDapp.ts, src/workflowOptions.ts, templates/nft-minting-dapp-template/frontend/config.ts, templates/nft-minting-dapp-template/frontend/constants.ts, templates/nft-minting-dapp-template/frontend/hooks/useGetCollectionData.ts, templates/nft-minting-dapp-template/frontend/pages/Mint/components/ConnectWalletAlert.tsx, templates/token-minting-dapp-template/frontend/config.ts, templates/token-minting-dapp-template/frontend/constants.ts, templates/token-minting-dapp-template/frontend/hooks/useGetAssetData.ts, templates/token-minting-dapp-template/frontend/pages/Mint/components/ConnectWalletAlert.tsx
Tested both template by running them locally
Doc PR https://github.com/aptos-labs/developer-docs/pull/578
=> Move collection addr and fa addr to env

CHANGELOG.md, src/generateDapp.ts, templates/boilerplate-template/README.md, templates/nft-minting-dapp-template/README.md, templates/token-minting-dapp-template/README.md, templates/token-staking-dapp-template/README.md
Based on user feedbacks, we noticed that
1. Instruct devs to start the dapp after the template generation flow doesnt make sense as they dont really know what to do with it.
2. Developers miss the documentation link.
This PR Instruct devs to read the README file on template generation and makes sure each template README file mentions the docs on aptos.dev
=> Update next steps instructions and update README file

.gitignore, CHANGELOG.md, templates/nft-minting-dapp-template/contract/sources/launchpad.move, templates/nft-minting-dapp-template/contract/tests/test_end_to_end.move, templates/nft-minting-dapp-template/frontend/hooks/useGetCollectionData.ts, templates/nft-minting-dapp-template/frontend/hooks/useGetCollections.tsx, templates/nft-minting-dapp-template/frontend/pages/Mint/components/HeroSection.tsx, templates/nft-minting-dapp-template/frontend/utils/Irys.ts, templates/nft-minting-dapp-template/frontend/view-functions/getAccountAPTBalance.ts, templates/nft-minting-dapp-template/frontend/view-functions/getActiveOrNextMintStage.ts, templates/nft-minting-dapp-template/frontend/view-functions/getMintEnabled.ts, templates/nft-minting-dapp-template/frontend/view-functions/getMintStageStartAndEndTime.ts, templates/nft-minting-dapp-template/frontend/view-functions/getRegistry.ts, templates/nft-minting-dapp-template/frontend/view-functions/getUserMintBalance.ts, templates/token-minting-dapp-template/contract/sources/launchpad.move, templates/token-minting-dapp-template/contract/tests/test_end_to_end.move, templates/token-minting-dapp-template/frontend/hooks/useGetAssetData.ts, templates/token-minting-dapp-template/frontend/hooks/useGetAssetMetadata.tsx, templates/token-minting-dapp-template/frontend/pages/Mint/components/HeroSection.tsx, templates/token-minting-dapp-template/frontend/utils/Irys.ts, templates/token-minting-dapp-template/frontend/view-functions/getAccountAPTBalance.ts, templates/token-minting-dapp-template/frontend/view-functions/getMintEnabled.ts, templates/token-minting-dapp-template/frontend/view-functions/getRegistry.ts, templates/token-minting-dapp-template/frontend/view-functions/getUserMintBalance.ts
- Add new view function to return user mint balance
- Store mint balance (i.e. how many token left to mint) instead of how many user has minted in the tracker, this is to keep consistency with token minter contract because token minter tracks balance left to mint instead of minted so far.
- Add a flag to config that can disable / enable mint
=> Fix token up to mint and add a flag to enable/disable mint

CHANGELOG.md, examples/aptogotchi-random-mint/src/context/WalletProvider.tsx, examples/aptos-friend/frontend/components/WalletProvider.tsx, templates/boilerplate-template/frontend/components/WalletProvider.tsx, templates/boilerplate-template/package.json, templates/nextjs-boilerplate-template/package.json, templates/nextjs-boilerplate-template/src/components/WalletProvider.tsx, templates/nft-minting-dapp-template/frontend/components/WalletProvider.tsx, templates/nft-minting-dapp-template/package.json, templates/token-minting-dapp-template/frontend/components/WalletProvider.tsx, templates/token-minting-dapp-template/package.json, templates/token-staking-dapp-template/frontend/components/WalletProvider.tsx, templates/token-staking-dapp-template/package.json
Based on user feedback, unknown wallets confusing them, i.e the `Dev T Wallet` which is mostly popular in Korea.
This PR opt in by default to the most popular wallets.
=> Support popular wallets in the wallet selector by default

CHANGELOG.md, examples/aptogotchi-keyless/package.json, examples/aptogotchi-random-mint/package.json, examples/aptos-friend/package.json, package.json, templates/boilerplate-template/package.json, templates/nextjs-boilerplate-template/package.json, templates/nft-minting-dapp-template/package.json, templates/token-minting-dapp-template/package.json, templates/token-staking-dapp-template/package.json
Upgrading the aptos-ts-sdk version following a hot fix https://github.com/aptos-labs/aptos-ts-sdk/pull/513
Ideally, the tool should install latest ts-sdk `1.x.x` version, but bumping the dependency version just to be safe
=> Upgrade aptos ts sdk dependency to `^1.28.0`

CHANGELOG.md, src/generateDapp.ts, src/utils/installAptosCli.ts
Following openUX feedback - Instead of installing the Aptos cli when user runs any of the `npm run move` commands, we install it as part of the wizard setup flow
=> Install the Aptos cli as part of the wizard setup

CHANGELOG.md, src/generateDapp.ts
When installing the aptos cli we use `npx` command to trigger the npm bin, but since we do it before dependencies are installed it is failing.
Moving the aptos cli installation to happen after dependencies are installed.
=> Install aptos cli after dependencies are installed

CHANGELOG.md, package.json, templates/custom-indexer-template/_gitignore, templates/custom-indexer-template/indexer/src/steps/extractor.rs
error reported by a community member, super appreciate him trying cad out
https://github.com/aptos-labs/aptos-developer-discussions/discussions/509
=> Fix indexer template and release

template-live-examples/nft-minting/contract/sources/launchpad.move, template-live-examples/nft-minting/contract/tests/test_end_to_end.move, templates/nft-minting-dapp-template/contract/sources/launchpad.move, templates/nft-minting-dapp-template/contract/tests/test_end_to_end.move
This PR solves 2 issues in the launchpad.move example.
When using this example template, we ran into an issue with the mint stages from token-minter. 
`minter::execute_earliest_stage` loops over the mint stages, and removes any inactive indexes from the mint_stages vector, until it finds and active stage and then returns that index. Since the inactive indexes have been removed, the returned index does not match the active mint stage. The active mint stage will always have index 0, since all earlier indexes have been removed for being inactive.
The launchpad.move module uses returned value from `execute_earliest_stage` as input for index when calling `minter::find_mint_stage_by_index`. It should just use `0` as input for index, as that is now the index for the active mint stage.
Also there …
=> Fixes for nft example launchpad.move

examples/aptos-friend/contract/sources/aptos_friend.move
Fix a small typo in the comments section of the aptos_friend.move file. Changed 'moduelr' to 'module'.
=> Fix typo in comment

CHANGELOG.md, templates/boilerplate-template/package.json, templates/boilerplate-template/vite.config.ts
This breaks the `build` because of max size, might be because of the ts-sdk size, but for now removing this plugin to unblock users
=> Remove `VitePWA`  plugin from Boilerplate templates
