aptos-labs/create-aptos-dapp

- templates/digital-asset-template/move/sources/launchpad.move
- templates/digital-asset-template/scripts/move/compile.js
- templates/digital-asset-template/scripts/move/publish.js
Update to address latest change in token minter https://github.com/aptos-labs/token-minter/pull/72
> Update nft contract for latest token minter

- templates/digital-asset-template/frontend/components/LaunchpadHeader.tsx
- templates/digital-asset-template/frontend/hooks/useGetCollections.tsx
- templates/digital-asset-template/frontend/pages/CreateCollection.tsx
- templates/digital-asset-template/frontend/pages/MyCollections.tsx
- templates/digital-asset-template/frontend/utils/Irys.ts
- templates/digital-asset-template/frontend/utils/aptosClient.ts
- templates/digital-asset-template/frontend/utils/assetsUploader.ts
Implementing the Create Collection and My Collections UI + asset uploader flow
Note: there is an issue with nft image not being loaded in wallet - will come back to it after
https://github.com/aptos-labs/create-aptos-dapp/assets/29798064/fef85374-4349-49cf-afd5-65e9f0a409a8
> Add launchpad UI for NFT template

- templates/digital-asset-template/move/sources/launchpad.move
Update token minter APIs to latest
> Update token minter APIs to latest

- templates/digital-asset-template/frontend/pages/Mint/components/Header.tsx
- templates/digital-asset-template/frontend/pages/Mint/components/HeroSection.tsx
- templates/digital-asset-template/frontend/pages/Mint/hooks/useMintData.ts
Adds real dates to the digital asset template
> Uses real times

- templates/digital-asset-template/frontend/pages/CreateCollection.tsx
https://github.com/aptos-labs/create-aptos-dapp/assets/29798064/c0fca969-7113-4278-ad11-85c26517894d
> Add time selection to mint stage

- src/generateDapp.ts
- Some dev life improvements to ignore some local files when generating a template locally
- UI and content Improvements for the final commands
> cli ui improvement

- templates/digital-asset-template/frontend/pages/CreateCollection.tsx
- templates/fungible-asset-template/frontend/pages/CreateFungibleAsset.tsx
we store APT in smallest unit (10e-8) onchain
> fix mint fee decimal

- templates/digital-asset-template/move/sources/launchpad.move
- templates/fungible-asset-template/move/sources/launchpad.move
> make mint fee optional and default to 0

- templates/digital-asset-template/move/sources/launchpad.move
- templates/fungible-asset-template/move/sources/launchpad.move
Tested locally with contract unit test
> Better error code in contract and sync common logic from NFT contract to FA contract

- package.json
- pnpm-lock.yaml
- src/generateDapp.ts
https://github.com/aptos-labs/create-aptos-dapp/assets/29798064/e63ba9ea-e349-4eb3-8d2b-6299317a120a
> Add spinner to wizard

- templates/digital-asset-template/frontend/components/WalletSelector.tsx
- templates/fungible-asset-template/frontend/components/WalletSelector.tsx
> Apply wallet adapter fix when there are no more wallets to show

- templates/digital-asset-template/frontend/pages/Mint/hooks/useMintData.ts
- templates/digital-asset-template/frontend/pages/Mint/index.tsx
- templates/digital-asset-template/frontend/utils/truncateAddress.ts
- templates/fungible-asset-template/frontend/pages/CreateFungibleAsset.tsx
- templates/fungible-asset-template/frontend/pages/Mint/components/HeroSection.tsx
- templates/fungible-asset-template/frontend/pages/Mint/hooks/useMintData.ts
- templates/fungible-asset-template/frontend/pages/Mint/index.tsx
- templates/fungible-asset-template/frontend/utils/helpers.ts
- templates/fungible-asset-template/frontend/utils/truncateAddress.ts
- Fixed some random errors in console
- Allows decimals to be used in fungible input
- Fixed issue when you couldn't proceed if you manually set max mint to 0
- Properly refreshes assets when account changes
- Disables minting if max supply has been met
> More ui bug fixes

- templates/digital-asset-template/frontend/pages/MyCollections.tsx
- templates/digital-asset-template/frontend/utils/Irys.ts
- templates/digital-asset-template/frontend/utils/assetsUploader.ts
- Use Irys estimateFolderPrice to estimate a folder price to upload
- add `?` to  collection.cdn_asset_uris because of indexer latency, it doesnt really solve the problem but at least page doesnt break
- We are now throwing errors for any upload issues
> Fix folder upload estimation issues

- templates/digital-asset-template/frontend/pages/CreateCollection.tsx
Royalty Percentage input should be optional to set on the UI and we dont need to block collection creation if user didnt set it
> [Digital Asset] fix Royalty input

- templates/digital-asset-template/frontend/pages/CreateCollection.tsx
When setting a value on an input, and then deleting it, it is translated into a `"NaN"` and fails submission. This fixes it
> [Digital Asset] Fix a bug when input a value and then deleting it

- templates/digital-asset-template/frontend/hooks/useGetCollections.tsx
- templates/digital-asset-template/frontend/pages/MyCollections.tsx
- templates/digital-asset-template/package.json
- templates/fungible-asset-template/frontend/hooks/useGetAssetMetadata.tsx
- templates/fungible-asset-template/package.json
Change to use TS SDK queries instead of custom graphql queries.
> Use sdk queries

- templates/digital-asset-template/frontend/pages/Mint/hooks/useMintData.ts
- templates/digital-asset-template/move/sources/launchpad.move
If mint end time is 100 years after mint start time, we consider mint end date to be infinity. Make sure frontend and contract both follow this approach.
tested e2e locally
> fix mint end date display when set to infinity

- templates/digital-asset-template/frontend/hooks/useGetCollections.tsx
- templates/digital-asset-template/frontend/pages/CreateCollection.tsx
- templates/digital-asset-template/frontend/pages/MyCollections.tsx
This addresses [Show message when indexer hasnt catched up (or attempt optimistic update)](https://www.notion.so/aptoslabs/Show-message-when-indexer-hasnt-catched-up-or-attempt-optimistic-update-f122c140873d4fd1a6fcfe0bf7b082cb). The collection page no longer crashes, we use react-query to refetch on an interval. My initial approach tried using optimistic updates with react query, but that turned out a bit more complicated and error prone than I think was worth it. This prevents the crash and eventually loads data when available.
> Refactors My Collection and useCollection to use react-query

- templates/digital-asset-template/.gitignore
- templates/fungible-asset-template/frontend/pages/CreateFungibleAsset.tsx
> More fixes

- templates/digital-asset-template/move/sources/launchpad.move
- templates/fungible-asset-template/move/sources/launchpad.move
no logic change, only doc change
> better docs for contracts

- templates/fungible-asset-template/frontend/App.tsx
- templates/fungible-asset-template/frontend/components/Header.tsx
- templates/fungible-asset-template/frontend/components/LaunchpadHeader.tsx
- templates/fungible-asset-template/frontend/components/UploadSpinner.tsx
- templates/fungible-asset-template/frontend/components/WalletProvider.tsx
- templates/fungible-asset-template/frontend/components/WalletSelector.tsx
- templates/fungible-asset-template/frontend/entry-functions/create_asset.ts
- templates/fungible-asset-template/frontend/entry-functions/mint_asset.ts
- templates/fungible-asset-template/frontend/hooks/useGetAssetData.ts
- templates/fungible-asset-template/frontend/hooks/useGetAssetMetadata.tsx
- templates/fungible-asset-template/frontend/main.tsx
- templates/fungible-asset-template/frontend/pages/CreateFungibleAsset.tsx
- templates/fungible-asset-template/frontend/pages/Mint/components/ConnectWalletAlert.tsx
- templates/fungible-asset-template/frontend/pages/Mint/components/HeroSection.tsx
- templates/fungible-asset-template/frontend/pages/Mint/components/OurStorySection.tsx
- templates/fungible-asset-template/frontend/pages/Mint/components/Socials.tsx
- templates/fungible-asset-template/frontend/pages/Mint/components/StatsSection.tsx
- templates/fungible-asset-template/frontend/pages/Mint/index.tsx
- templates/fungible-asset-template/frontend/pages/MyFungibleAssets.tsx
- templates/fungible-asset-template/frontend/utils/Irys.ts
- templates/fungible-asset-template/frontend/view-functions/accountBalance.ts
same as https://github.com/aptos-labs/create-aptos-dapp/pull/121
> Refactor and clean up fungible asset template

- .github/workflows/build-biolerplate-template.yml
- .github/workflows/build-digital-asset-template.yml
- .github/workflows/build-fungible-asset-template.yml
https://aptos-org.slack.com/archives/C03EP0XM99D/p1720620498098609
> Fix github actions concurrency

- templates/boilerplate-template/frontend/components/WalletSelector.tsx
- templates/boilerplate-template/package.json
- templates/digital-asset-template/frontend/components/WalletSelector.tsx
- templates/digital-asset-template/package.json
- templates/fungible-asset-template/frontend/components/WalletSelector.tsx
- templates/fungible-asset-template/package.json
> Add adapter AptosConnect educational screen to each template

- package.json
Something was messed up with the previous release
> Bump to version 0.0.15

- examples/randomness/package.json
- src/generateDapp.ts
- src/generateExample.ts
- src/utils/helpers.ts
- Make runCommand return a Promise to not block execution context
- Remove unneeded step when generating an example
- Add dotenv dependency to Randomness example
> Some fixes and improvements

- index.ts
- src/generateDapp.ts
- src/generateExample.ts
- src/telemetry.ts
- src/types.ts
This PR adds the `example` command to our telemetry tool
> Add example command data to telemetry

- examples/aptos-friend/move/sources/aptos_friend.move
- examples/aptos-friend/move/tests/test_end_to_end.move
> Move aptos friend contract test to its own file

- README.md
Add Prerequisites section to readme
> add Prerequisites section to readme

- package.json
- src/generateDapp.ts
- src/types.ts
- src/workflowOptions.ts
1. Adds a walkthrough video for a template
2. Improve the instructions UI by adding docs and video links on the CLI while dependencies are being installed
https://github.com/user-attachments/assets/c3e29741-7179-40e1-9f2d-0b5c75cecf3e
> Improve instructions UI

- templates/boilerplate-template/scripts/move/publish.js
- templates/nft-minting-dapp-template/scripts/move/compile.js
- templates/nft-minting-dapp-template/scripts/move/publish.js
- templates/nft-minting-dapp-template/scripts/move/upgrade.js
- templates/token-minting-dapp-template/scripts/move/compile.js
- templates/token-minting-dapp-template/scripts/move/publish.js
- templates/token-minting-dapp-template/scripts/move/upgrade.js
- templates/token-staking-dapp-template/scripts/move/compile.js
- templates/token-staking-dapp-template/scripts/move/publish.js
- templates/token-staking-dapp-template/scripts/move/upgrade.js
- Hot fix for latest CLI version
- Throw meaningful errors when needed on move scripts
> Hot fix cli and throw meaningful errors

- templates/boilerplate-template/move/sources/message_board.move
- templates/boilerplate-template/move/tests/test_end_to_end.move
- templates/nft-minting-dapp-template/move/sources/launchpad.move
- templates/nft-minting-dapp-template/move/tests/test_end_to_end.move
- templates/token-minting-dapp-template/move/sources/launchpad.move
- templates/token-minting-dapp-template/move/tests/test_end_to_end.move
Didn't change any existing contract logics, just move unit test to its own file. 
Passed existing unit tests.
> fmt and move unit test to own file

- CHANGELOG.md
- package.json
```
- Code cleanup, always use env var from constants
- Rename `collection_id` to `collection_address` in the NFT minting template
- Move `collection_address` and `fa_address` from `config.ts` to the `.env` file in the minting templates
- Rename template `move` folder to `contract`
- Update next steps instructions when generating a template to follow README file
- Make sure each temlpate README file mentions the template doc on aptos.dev
```
> Bump version to 0.0.24

- CHANGELOG.md
- my-aptos-dapp/.gitignore
- my-aptos-dapp/README.md
- my-aptos-dapp/contract/.gitignore
- my-aptos-dapp/contract/Move.toml
- my-aptos-dapp/contract/sources/message_board.move
- my-aptos-dapp/contract/tests/test_end_to_end.move
- my-aptos-dapp/package.json
- my-aptos-dapp/scripts/move/compile.js
- my-aptos-dapp/scripts/move/publish.js
- my-aptos-dapp/scripts/move/test.js
- my-aptos-dapp/scripts/move/upgrade.js
- src/utils/createModulePublisherAccount.ts
- src/utils/generateTemplateEnvFile.ts
> Add a better error handling when creating a module publisher account

- CHANGELOG.md
- examples/aptogotchi-keyless/package.json
- examples/aptogotchi-random-mint/package.json
- examples/aptos-friend/package.json
- package.json
- src/utils/installAptosCli.ts
- template-live-examples/token-minting/package.json
- template-live-examples/token-staking/package.json
- templates/boilerplate-template/package.json
- templates/custom-indexer-template/package.json
- templates/nextjs-boilerplate-template/package.json
- templates/nft-minting-dapp-template/package.json
- templates/token-minting-dapp-template/package.json
- templates/token-staking-dapp-template/package.json
- Bumping the ts-sdk dep to latest version 1.30.0.
- `npx aptos` command is not updated automatically on every run
> Bump ts-sdk version

- CHANGELOG.md
- templates/nft-minting-dapp-template/frontend/utils/Irys.ts
- templates/nft-minting-dapp-template/package.json
- templates/token-minting-dapp-template/frontend/utils/Irys.ts
- templates/token-minting-dapp-template/package.json
Irys updated its flows and SDK, this PR upgrade the NFT and Token minting templates to the new Irys flow
* https://www.npmjs.com/package/@irys/sdk
* https://docs.irys.xyz/build/d/sdk/setup#aptos
* https://docs.irys.xyz/build/d/irys-in-the-browser#aptos
> Upgrade to the new Irys SDK

- templates/custom-indexer-template/indexer/src/steps/extractor.rs
> only index successful tx

- CHANGELOG.md
- templates/boilerplate-template/package.json
- templates/custom-indexer-template/package.json
- templates/nextjs-boilerplate-template/package.json
- templates/nft-minting-dapp-template/package.json
- templates/token-minting-dapp-template/package.json
- templates/token-staking-dapp-template/package.json
Bump the aptos-wallet-adapter package in all templates
> Bump wallet adapter version

- examples/aptogotchi-keyless/contract/Move.toml
- examples/aptogotchi-random-mint/contract/Move.toml
- examples/aptos-friend/contract/Move.toml
- examples/build-e2e-dapp-guide/contract/Move.toml
- template-live-examples/boilerplate/contract/Move.toml
- template-live-examples/nft-minting/contract/Move.toml
- template-live-examples/token-minting/contract/Move.toml
- template-live-examples/token-staking/contract/Move.toml
- templates/boilerplate-template/contract/Move.toml
- templates/contract-boilerplate-template/contract/Move.toml
- templates/custom-indexer-template/contract/Move.toml
- templates/nextjs-boilerplate-template/contract/Move.toml
- templates/nft-minting-dapp-template/contract/Move.toml
- templates/token-minting-dapp-template/contract/Move.toml
- templates/token-staking-dapp-template/contract/Move.toml
Uses aptos-framework instead of aptos-core
> [move] Update move dependencies to use framework instead of aptos-core

- CHANGELOG.md
- templates/boilerplate-template/frontend/main.tsx
- templates/boilerplate-template/package.json
- templates/boilerplate-template/vite.config.ts
- templates/boilerplate-template/vite.polyfills.ts
applied @iskysun96 suggestion in https://github.com/aptos-labs/create-aptos-dapp/issues/298
> fix surf polyfill
